# Generated by Django 3.1.3 on 2020-11-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_auto_20201116_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_list',
            old_name='bought',
            new_name='complete',
        ),
    ]
